### PR TITLE
Add source and gemspec command-line options

### PR DESCRIPTION
**Pull request by adangel**
This is #3 rebased against current master and slightly adjusted.

### CODE REVIEW

**Comment by flavorjones** [comment]
Thank you for rebasing this! :heart: Merging and I'll cut a release this weekend.

**Comment by flavorjones** [comment]
Quick question for you: when I specify `true` for the gemspec, I get both `gemspec` and the list of `gem` declarations. Is that intentional? I'm not sure I understand that use case.

**Comment by adangel** [comment]
Thanks for merging!

I've used the approach from the original PR and if gemspec is true, then both gemspec and the gem declarations end up in the Gemfile.

This leads to the following warning for each gem:

    Your Gemfile lists the gem hoe-bundler (~> 1.2) more than once.
    You should probably keep only one of them.
    While it's not a problem now, it could cause errors if you change the version of one of them later.

It doesn't seem to be a problem and for my project, the version should always be the same, since the gemspec and Gemfile are generated from the same source.

Removing the gems and just leaving the gemspec removes this warning.
I'll create a new PR for this case.

**Comment by flavorjones** [comment]
Thank you again!

**Comment by flavorjones** [comment]
shipped in v1.5.0

**Pull request merged**
